dist: xenial
language: cpp
compiler:
   - gcc
#  - clang 
jdk:
   - openjdk11
addons:
  apt:
    update: true
    allow_unauthenticated: yes
    packages:
    - python
    - python-dev

before_install:
    - ./waf configure

script:
    - ./waf
os:
- linux
